### ISSUE TITLE
Anchor a rencontré une erreur

### ISSUE THREAD

**Issue by koalin872** [greymass/anchor#1058]
TypeError: Cannot read property 'EOS7e9Rt5whTrQDgkeU3mevPu1ypjWv9Dut1iEB5RbDQCWf6sjALe' of undefined
    at file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:9:1421603
    at Array.map (<anonymous>)
    at g.render (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:9:1421271)
    at La (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:141:69974)
    at Ra (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:141:69769)
    at gi (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:141:105568)
    at ul (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:141:96815)
    at il (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:141:96740)
    at $i (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:141:93770)
    at file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:141:45412

**Comment by aaroncox** [comment]
Can you provide more information? It sounds like the wallet was setup incorrectly somehow or there's a bug. I'm not sure how you got to this point.
