### ISSUE TITLE
Error on Resource 

### ISSUE THREAD

**Issue by dzuvingulie** [greymass/anchor#1097]
Error>

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bcolor%2C%20content%2C%20size%2C%20style%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _s (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:51587)
    at file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:56461
    at Ti (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:65888)
    at Li (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:70071)
    at Ri (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:69769)
    at ga (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:105568)
    at lu (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:96815)
    at au (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:96740)
    at $a (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:93770)
    at file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:248:45412

**Comment by aaroncox** [comment]
Any more information? 

Was it when opening the resources section, or performing an action? Unfortunately the error message doesn't display anything actionable.

**Comment by dzuvingulie** [comment]
It was when opening the resource section....
Strange.. I was low on Cpu after performing many craftings.. and the issue
appeared on resource section

**Comment by FinaryR3** [comment]
I'm encountering the same error quite often.

**Comment by SpaceCowboy0420** [comment]
Same error with me. I think it happened when i updated my Anchor wallet from 1.1.xxx to 1.2.2.

**Comment by aaroncox** [comment]
There must be a specific set of conditions for accounts that we are just not seeing. Would anyone mind sharing an account name of one of the accounts that's experiencing this issue?

**Comment by SpaceCowboy0420** [comment]
> There must be a specific set of conditions for accounts that we are just not seeing. Would anyone mind sharing an account name of one of the accounts that's experiencing this issue?
> 
> Feel free to email it to [team@greymass.com](mailto:team@greymass.com) if you'd rather not post to github.

Hi Aaron, My account's that im using is ispeyscowboy@owner for the Wax network

**Comment by aaroncox** [comment]
Thanks for reporting an account as an example 👍 

We've identified the issue and the next release will get this fixed.
