### ISSUE TITLE
Anchor Wallet Desktop - Resources Tab error

### ISSUE THREAD

**Issue by tseyt** [greymass/anchor#1116]
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bcolor%2C%20content%2C%20size%2C%20style%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _s (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:248:51587)
    at file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:248:56461
    at Ti (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:248:65888)
    at Li (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:248:70071)
    at Ri (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:248:69769)
    at ga (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:248:105568)
    at lu (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:248:96815)
    at au (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:248:96740)
    at $a (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:248:93770)
    at file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:248:45412

**Comment by aaroncox** [comment]
Which version? I believe this is resolved if you upgrade to 1.2.3.
