### ISSUE TITLE
Error importing an account created with "create.anchor.link"

### ISSUE THREAD

**Issue by camillo777** [greymass/anchor#1211]
MACOS Desktop Anchor app

TypeError: Cannot read property 'map' of undefined
    at i.value (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:631032)
    at Wa (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3926075)
    at _a (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3925870)
    at Su (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3961484)
    at bc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3952925)
    at yc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3952850)
    at uc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3949880)
    at file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3901521
    at t.unstable_runWithPriority (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:4432695)
    at Qo (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3901230)

**Comment by aaroncox** [comment]
Which version of desktop was this?

**Comment by camillo777** [comment]
Anchor v 1.3.1
macOS Catalina 10.15.7 (19H1519)

Actually it happened creating the backup

Il giorno mer 17 nov 2021 alle ore 19:12 Aaron Cox ***@***.***>
ha scritto:
