### ISSUE TITLE
Invalid public key error when trying to select the "Import an existing account"

### ISSUE THREAD

**Issue by petervalencic** [greymass/anchor#1232]
I have got this error while trying to register the account with a private key:

![image](https://user-images.githubusercontent.com/10866388/148596694-df10dbb2-467c-4d52-80d7-789a06f1e39f.png)

**Comment by aaroncox** [comment]
Out of curiosity where did the private key come from? Is it Appics by chance?

**Comment by petervalencic** [comment]
Hi Aaron, the step I have done that was: Home -> Manage Wallets -> Import Accounts -> Existing Account -> Import Private Key (when I have pressed this option the app crashed)...

Today it works well.. (don't know what was the reason yesterday)..

**Comment by lukestokes** [comment]
Error: Invalid public key string
    at Function.from (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:210719)
    at file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:2217506
    at Array.forEach (<anonymous>)
    at c.value (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:2217450)
    at Wa (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3926265)
    at _a (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3926060)
    at Su (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3961674)
    at bc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3953115)
    at yc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3953040)
    at uc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3950070)

Same error here. Just clicked on the button to import a key. That's it.

**Comment by lukestokes** [comment]
Error: Invalid public key string
    at Function.from (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:210719)
    at file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:2217506
    at Array.forEach (<anonymous>)
    at c.value (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:2217450)
    at Wa (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3926265)
    at _a (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3926060)
    at Su (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3961674)
    at bc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3953115)
    at yc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3953040)
    at uc (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:2:3950070)

Same error here. Just clicked on the button to import a key. That's it.

**Comment by iht76** [comment]
same here:

Error: Invalid public key string
    at Function.from (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:210719)
    at file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:2217506
    at Array.forEach (<anonymous>)
    at c.value (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:2217450)
    at Wa (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3926265)
    at _a (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3926060)
    at Su (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3961674)
    at bc (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3953115)
    at yc (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3953040)
    at uc (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:3950070)


it worked fine importing 1 key , and after it started giving the above

**Comment by louis-88** [comment]
Any News here? I'm running the latest version here from Github. Have all the time thesame Error.

```                    throw new Error("Invalid public key string")
```
