### ISSUE TITLE
wallet dekstop windows

### ISSUE THREAD

**Issue by KU74N9** [greymass/anchor#1299]
### Description

Error: [DecimalError] Invalid argument: null
    at new i (file:///E:/ANCHOR%20WALLET/resources/app.asar/dist/renderer.main.prod.js:2:3268558)
    at i (file:///E:/ANCHOR%20WALLET/resources/app.asar/dist/renderer.main.prod.js:2:3268027)
    at Object.t.onChange (file:///E:/ANCHOR%20WALLET/resources/app.asar/dist/renderer.main.prod.js:2:2178362)
    at i.<anonymous> (file:///E:/ANCHOR%20WALLET/resources/app.asar/dist/renderer.main.prod.js:2:1390037)
    at vi (file:///E:/ANCHOR%20WALLET/resources/app.asar/dist/renderer.main.prod.js:2:4107302)
    at su (file:///E:/ANCHOR%20WALLET/resources/app.asar/dist/renderer.main.prod.js:2:4142325)
    at wc (file:///E:/ANCHOR%20WALLET/resources/app.asar/dist/renderer.main.prod.js:2:4159801)
    at t.unstable_runWithPriority (file:///E:/ANCHOR%20WALLET/resources/app.asar/dist/renderer.main.prod.js:2:4636213)
    at Qo (file:///E:/ANCHOR%20WALLET/resources/app.asar/dist/renderer.main.prod.js:2:4103772)
    at Ac (file:///E:/ANCHOR%20WALLET/resources/app.asar/dist/renderer.main.prod.js:2:4156467)

### Platform

Desktop (Windows)

### Anything else?

![Screenshot_32](https://user-images.githubusercontent.com/66903770/184463940-d29acc40-1365-449a-9263-268bfbc2647e.jpg)

**Comment by aaroncox** [comment]
What were you trying to do? What network was this on?

It looks like you've configured a custom network (the ? as the network icon in the upper left), did you misdefine any of the configuration parameters?
