### ISSUE TITLE
error (Uncaught Exception)

### ISSUE THREAD

**Issue by jeee** [greymass/anchor#845]
running anchor from linux-anchor-wallet-1.0.0-armv7l.deb gives me this only:

@babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning.
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.M7rGDL: wrong ELF class: ELFCLASS64
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Anchor Wallet/resources/app.asar/node_modules/usb/usb.js:5:38)
    at Object.<anonymous> (/opt/Anchor Wallet/resources/app.asar/node_modules/usb/usb.js:417:3)

**Comment by aaroncox** [comment]
Thanks for the heads up on this, we'll investigate and see what this means.
