### ISSUE TITLE
Unable to connect to the EOS blockchain.

### ISSUE THREAD

**Issue by huanan67** [greymass/anchor#882]
Anchor has encountered an error
Error Message
ReferenceError: I18n is not defined
    at v.render (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:9:1005732)
    at La (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:72:69974)
    at Ra (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:72:69769)
    at gi (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:72:105568)
    at ul (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:72:96815)
    at il (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:72:96740)
    at $i (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:72:93770)
    at file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:72:45412
    at t.unstable_runWithPriority (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:96:3844)
    at Gr (file:///Applications/Anchor%20Wallet.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:72:45121)

**Comment by aaroncox** [comment]
Few questions for you:

- Which version is this? 
- What operating system?
- Is this happening on launch or when you click something specific?

**Comment by huanan67** [comment]
> Few questions for you:
> 
> * Which version is this?
> * What operating system?
> * Is this happening on launch or when you click something specific?

version: 1.0.1
OS: Mac 10.15.1
This happened at launch.

details as follows in Anchor:

Unable to connect to the EOS blockchain.
https://eos.greymass.com is not responding to requests.

Connection Error
Cannot read property 'data' of undefined

**Comment by huanan67** [comment]
> Few questions for you:
> 
> * Which version is this?
> * What operating system?
> * Is this happening on launch or when you click something specific?

Network Problems, and it isn't solved, thanks

**Comment by aaroncox** [comment]
I think we found the issue - we'll get a fix included in the next release that resolves this.

**Comment by aaroncox** [comment]
Also - on that error page you should be able to click "Edit Blockchain" and specify a new API endpoint to get around the error right now. The issue I believe is that for some reason you cannot connect to our default API endpoint (eos.greymass.com).

If you visit eos.greymass.com in your web browser, does it load at all?
