### ISSUE TITLE
I received the following error 

### ISSUE THREAD

**Issue by pairmike** [greymass/anchor#907]
Error: Could not call remote function 'e'. Check that the function signature is correct. Underlying error: [sprintf] unexpected placeholder
Underlying stack: SyntaxError: [sprintf] unexpected placeholder
    at Function.parse (/Applications/Anchor Wallet.app/Contents/Resources/app.asar/webpack:/app/main.prod.js:112614:19)
    at apply (/Applications/Anchor Wallet.app/Contents/Resources/app.asar/webpack:/app/main.prod.js:112461:30)
    at vsprintf (/Applications/Anchor Wallet.app/Contents/Resources/app.asar/webpack:/app/main.prod.js:112624:20)
    at Object.process (/Applications/Anchor Wallet.app/Contents/Resources/app.asar/webpack:/app/main.prod.js:112409:27)
    at forEach (/Applications/Anchor Wallet.app/Contents/Resources/app.asar/webpack:/app/main.prod.js:114441:76)
    at Array.forEach (<anonymous>)
    at Object.handle (/Applications/Anchor Wallet.app/Contents/Resources/app.asar/webpack:/app/main.prod.js:114440:16)
    at t.extendTranslation (/Applications/Anchor Wallet.app/Contents/Resources/app.asar/webpack:/app/main.prod.js:114698:29)
    at t.apply (/Applications/Anchor Wallet.app/Contents/Resources/app.asar/webpack:/app/main.prod.js:114658:20)
    at t.value (/Applications/Anchor Wallet.app/Contents/Resources/app.asar/webpack:/app/main.prod.js:116136:80)

    at electron/js2c/browser_init.js:6712:21
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6597:27)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3873:23)
    at WebContents.emit (events.js:210:5)

**Comment by aaroncox** [comment]
Give 1.0.4 a try and let us know if that resolves the issue 👍
