### ISSUE TITLE
Error Opening Wallet Assigned to UX Blockchain with Version 1.1.0

### ISSUE THREAD

**Issue by tocha5202** [greymass/anchor#966]
No issues with UX blockchain with opening wallet using Version 1.0.5 but the version 1.1.1 screen freezes with below errors after opening the wallet. Tried also with a fresh install., also different directories. Using Windows 10.

TypeError: Cannot destructure property 'precision' of 't.__contracts[l.toUpperCase(...)]' as it is undefined.
    at A.render (file:///C:/BC/Anchor/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:9:1535414)
    at La (file:///C:/BC/Anchor/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:69974)
    at Ra (file:///C:/BC/Anchor/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:69769)
    at gi (file:///C:/BC/Anchor/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:105568)
    at ul (file:///C:/BC/Anchor/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:96815)
    at il (file:///C:/BC/Anchor/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:96740)
    at $i (file:///C:/BC/Anchor/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:93770)
    at file:///C:/BC/Anchor/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:45412
    at t.unstable_runWithPriority (file:///C:/BC/Anchor/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:96:3844)
    at Gr (file:///C:/BC/Anchor/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:45121)

**Comment by aaroncox** [comment]
This should be resolved in 1.1.1 now:

https://github.com/greymass/anchor/releases/tag/v1.1.1

Give it a shot and feel free to reopen this issue if the error persists.

**Comment by tocha5202** [comment]
many thx Aaron....issue resolved...
