### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by asscror** [greymass/anchor#991]
TypeError: Cannot read property '0' of undefined
    at c.render (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:9:1178178)
    at La (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:69974)
    at Ra (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:69769)
    at gi (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:105568)
    at ul (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:96815)
    at il (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:96740)
    at $i (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:93770)
    at file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:45412
    at t.unstable_runWithPriority (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:96:3844)
    at Gr (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:72:45121)

**Comment by aaroncox** [comment]
What were you trying to do when this happened? Mind sharing a screenshot of where it was at in the interface?

**Comment by asscror** [comment]
Anchor wallet is forced to revive. He did this when I wanted to vote for eos governance, I will try again and if it happens again I would make a screenshot

**Comment by asscror** [comment]
![anchor](https://user-images.githubusercontent.com/37270006/93641239-3edd8080-f9fc-11ea-9033-c14aba9b0e37.PNG)

**Comment by asscror** [comment]
what surprises me is that I have 2 eos accounts, and I did the same operation with the 1st account, no worries ... it's only with the one

**Comment by aaroncox** [comment]
Thanks for the additional info, we'll dig into this soon and get a fix in the next release. I think I see what's causing the problem, but just need to do some testing to confirm.

**Comment by aaroncox** [comment]
It looks like you did manage to vote - and I'm assuming it's because it was attempting to vote for an unregistered producer. I think we have a fix for this in place for the next release.
